services:
  app:
    container_name: "leptos-app"
    build:
      context: .
      dockerfile: ./ruuderie_ai_app/Dockerfile
      args:
        - USERNAME=${USERNAME:-user}
        - USER_ID=${USER_ID:-1000}
        - USER_GID=${USER_GID:-1000}
    working_dir: "/app"
    volumes:
      - ./ruuderie_ai_app:/app:cached
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14.1
    container_name: "postgres-db"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: