[package]
name = "backend"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
app = { path = "../app", default-features = false }
entity = { path = "../entity" }
dotenv = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
tracing = { workspace = true, features = ["async-await", "log"] }
axum = { version = "0.7.4" ,features = ["tokio"]}
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
sea-orm = { version = "0.12", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-uuid",
    "with-json",
    "with-chrono",
] }
cfg-if = "1.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
console_error_panic_hook = "0.1.7"
contentful = "0.8.0"
http = "1.0.0"
leptos = { version = "0.6.14" }
leptos_axum = { version = "0.6.13" }
leptos_meta = { version = "0.6.5" }
leptos_router = { version = "0.6.5" }
tower = "0.4.13"
tower-http = { version = "0.5.1", features = ["cors", "fs", "sensitive-headers", "trace", "tracing"] }
anyhow = "1.0.75"
axum-macros = "0.4.1"
bigdecimal = { version = "0.4.1", features = ["serde"] }
log = "0.4.17"
simple_logger = "5.0.0"
tokio = { version = "1.39.3", features = ["full"] }
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "time"] }

