[package]
name = "backend"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
app = { path = "../app", default-features = false, features = ["ssr"] }
derive_more = { workspace = true }
entity = { path = "../entity" }
http = { workspace = true }
dotenv = { workspace = true }
leptos = { workspace = true, features = ["serde", "ssr"] }
leptos_axum = { workspace = true }
leptos_meta = { workspace = true, features = ["ssr"] }
leptos_router = { workspace = true, features = ["ssr"] }
sea-orm = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
tracing = { workspace = true, features = ["async-await", "log"] }
tower = "0.4.13"
tower-http = { version = "0.5.1", features = ["cors", "fs", "sensitive-headers", "trace", "tracing"] }
anyhow = "1.0.75"
axum-macros = "0.4.1"
bigdecimal = { version = "0.4.1", features = ["serde"] }
log = "0.4.17"
simple_logger = "5.0.0"
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mio = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true ,features = ["tokio"]}
tracing-subscriber = { workspace = true, features = ["env-filter", "json", "time"] }

[features]
default = ["ssr"]
ssr = ["leptos/ssr"]