-- 1. Eliminate Duplicate Job rows generated by repeated earlier migrations without conflict handlers
DELETE FROM jobs
WHERE id IN (
  SELECT id FROM (
    SELECT id, ROW_NUMBER() OVER(PARTITION BY company, role, date_range ORDER BY id) AS row_num
    FROM jobs
  ) t WHERE t.row_num > 1
);

-- 2. Add Employment Taxonomy columns
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS employment_type TEXT NOT NULL DEFAULT 'DirectHire';
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS parent_company TEXT;

-- 3. Migrate existing is_client_project definitions into the new semantic taxonomy
UPDATE jobs 
SET employment_type = 'CorpToCorp', parent_company = 'Oplyst International, LLC' 
WHERE is_client_project = true;

UPDATE jobs 
SET employment_type = 'DirectHire' 
WHERE is_client_project = false;

-- 4. Drop the legacy taxonomy identifier safely
ALTER TABLE jobs DROP COLUMN IF EXISTS is_client_project;
