[package]
name = "entity"
publish = false
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[lib]
name = "entity"
path = "src/lib.rs"

[dependencies]
migration = { path = "../migration" }
bcrypt = { workspace = true }
serde = { workspace = true, features = [
    "derive",
    "serde_derive",
    "alloc",
    "rc",
] }
chrono = { version = "0.4.31", features = ["serde", "alloc"] }
dotenvy = "0.15.7"
figment = { version = "0.10.19", features = [
    "toml",
    "json",
    "env",
    "yaml",
], optional = true }
sea-orm = { version = "0.12.3", features = [
    "with-chrono",
    "with-json",
    "with-uuid",
    "sqlx-postgres",
    "runtime-tokio-rustls",
] }
uuid = { version = "1.4.1", features = ["v4", "v7"] }
rand = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
[features]
default = ["figment"]
