[package]
name = "frontend"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
app = { path = "../app", default-features = false, features = ["hydrate"] }
leptos = { workspace = true, features = ["hydrate"] }
leptos_meta = { workspace = true, features = ["hydrate"] }
leptos_router = { workspace = true, features = ["hydrate"] }
leptonic = { workspace = true, features = ["hydrate"] }
tracing.workspace = true
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
tracing-wasm = "0.2.1"
wasm-bindgen = "0.2.87"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
chrono = { workspace = true, features = ["serde", "wasmbind"] }
uuid = { workspace = true, features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
    "js",
] }

[features]
default = ["hydrate"]
hydrate = [
    "leptos/hydrate",
    "leptos_meta/hydrate",
    "leptos_router/hydrate",
    "leptonic/hydrate",
]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "leptonic/ssr"]

[package.metadata.leptonic]
style-dir = "style"
js-dir = "public/js"

[package.metadata.leptos]
# The name used by wasm-bindgen/cargo-leptos for the JS/WASM bundle
output-name = "ruuderie-ai"

# The site root folder is where cargo-leptos generate all output
site-root = "target/site"

# The site-root relative folder where all compiled output (JS, WASM and CSS) is written
site-pkg-dir = "pkg"

# [Optional] The source CSS file. If it ends with .sass or .scss then it will be compiled by dart-sass into CSS
style-file = "style/main.css"

# Assets source dir. All files found here will be copied and synchronized to site-root
assets-dir = "public"

# The IP and port (ex: 127.0.0.1:3000) where the server serves the content
site-addr = "127.0.0.1:3000"

# The port to use for automatic reload monitoring
reload-port = 3001

# [Optional] Command to use when running end2end tests
end2end-cmd = "npx playwright test"
end2end-dir = "end2end"

# The browserlist query used for optimizing the CSS
browserquery = "defaults"

# Set by cargo-leptos watch when building with that tool
watch = false

# The environment Leptos will run in, usually either "DEV" or "PROD"
env = "DEV"

# The features to use when compiling the lib target
lib-features = ["hydrate"]

# If the --no-default-features flag should be used when compiling the lib target
lib-default-features = false

# The profile to use for the lib target when compiling for release
lib-profile-release = "wasm-release"
